name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '24 11 * * 1'

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
        - uses: actions/setup-go@v4
          with:
            go-version: '1.20.x'
            cache: false
        - uses: actions/checkout@v3
        - name: golangci-lint
          uses: golangci/golangci-lint-action@v3
          with:
            # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
            version: latest
