on: [pull_request]
name: Lint
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@master
        with:
          version: v1.52.1
          github-token: ${{ secrets.github_token }}
